accounts/urls.py
from django.urls import path, include
from . import views


app_name = 'accounts'

urlpatterns = [

    path('signup', views.signup, name='signup'),
    path('profile/', views.profile, name='profile'),
    path('profile_edit', views.profile_edit, name='profile_edit'),
]

contact/urls.py
from django.urls import path, include
from . import views


app_name = 'contact'

urlpatterns = [

    path('', views.contact, name='contact'),

]

job/urls.py
from django.urls import path, include
from . import views


app_name = 'job'

urlpatterns = [

    path('', views.job_list, name='job_list'),
    path('add', views.add_job, name='add_job'),
    path('<slug:slug>', views.job_detail, name='job_detail'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('admin/', admin.site.urls),
    path('jobs/', include('job.urls', namespace='jobs')),
    path('contact/', include('contact.urls', namespace='contact')),

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


# Create your models here.


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone_number = models.CharField(max_length=15)
    image = models.ImageField(upload_to='profile/')

    def __str__(self):
        return str(self.user)


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

blog/models.py
from django.db import models

# Create your models here.

contact/models.py
from django.db import models

# Create your models here.

home/models.py
from django.db import models

# Create your models here.

job/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User

# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name

# Customize iamge name when uploaded


def image_upload(instance, filename):
    image_name, extention = filename.split(".")
    return "jobs/%s.%s" % (instance.id, extention)


class Job(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    JOB_TYPE = [
        ('Full Time', 'Full Time'),
        ('Part Time', 'Part Time'),
    ]
    title = models.CharField(max_length=50)
    # loaction
    job_type = models.CharField(choices=JOB_TYPE, max_length=50)
    description = models.TextField(max_length=1000)
    vacancy = models.IntegerField(default=1)
    salary = models.IntegerField(default=0)
    experience = models.IntegerField(default=0)
    published_at = models.DateField(auto_now=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    image = models.ImageField(upload_to=image_upload)

    slug = models.SlugField(null=True, blank=True)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Job, self).save(*args, **kwargs)


class Applicant(models.Model):
    job = models.ForeignKey(Job, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    email = models.EmailField(max_length=254)
    website = models.URLField(max_length=200)
    cv = models.FileField(upload_to='resumes/')
    cover_letter = models.TextField(max_length=500)
    applied_at = models.DateField(auto_now=True)

    def __str__(self):
        return self.name

accounts/views.py
from django.shortcuts import render, redirect
from .form import SignupForm, ProfileForm, UserForm
from django.urls import reverse
from django.contrib.auth import authenticate, login
from pip._vendor.urllib3 import request
from .models import Profile
# Create your views here.


def signup(request):
    form = SignupForm()
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            user = authenticate(username=username, password=password)
            login(request, user)

            return redirect('accounts/profile')

    context = {

        'form': form

    }
    return render(request, 'registration/signup.html', context)


def profile(request):
    profile = Profile.objects.get(user=request.user)

    context = {
        'profile': profile
    }
    return render(request, 'profile.html', context)


def profile_edit(request):

    profile = Profile.objects.get(user=request.user)
    profileform = ProfileForm(instance=profile)
    userform = UserForm(instance=request.user)

    if request.method == 'POST':
        profileform = ProfileForm(
            request.POST, request.FILES, instance=profile)

        userform = UserForm(request.POST, instance=request.user)
        if profileform.is_valid() and userform.is_valid():
            profileform.save()
            userform.save()
            return redirect('accounts:profile')

    context = {
        'profileform': profileform,
        'userform': userform
    }

    return render(request, 'profile_edit.html', context)

blog/views.py
from django.shortcuts import render

# Create your views here.

contact/views.py
from django.shortcuts import render
from django.core.mail import send_mail
from django.conf import settings


# Create your views here.


def contact(request):

    if request.method == 'POST':
        subject = request.POST['subject']
        from_email = request.POST['email']
        message = request.POST['message']

        send_mail(
            subject,
            message,
            from_email,
            [settings.EMAIL_HOST_USER],
        )

    return render(request, 'contact.html')

home/views.py
from django.shortcuts import render

# Create your views here.

job/views.py
from django.core.paginator import Paginator
from django.shortcuts import redirect, render
from .models import Job
from .form import ApplicantForm, JobForm
from .filter import JobFilter
from django.urls import reverse
from django.contrib.auth.decorators import login_required


# Create your views here.


def job_list(request):
    jobs = Job.objects.all()
    jobs_filter = JobFilter(request.GET, queryset=jobs)
    jobs = jobs_filter.qs

    paginator = Paginator(jobs, 5)  # Show 5 contacts per page.

    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'jobs': page_obj,
        'jobs_num': jobs,
        'jobs_filter': jobs_filter


    }
    return render(request, 'job/job_list.html', context)


def job_detail(request, slug):
    job = Job.objects.get(slug=slug)
    form = ApplicantForm()

    if request.method == 'POST':
        form = ApplicantForm(request.POST, request.FILES)
        if form.is_valid():
            myform = form.save(commit=False)
            myform.job = job
            myform.save()

    context = {
        'job': job,
        'form': form

    }
    return render(request, 'job/job_detail.html', context)


@login_required
def add_job(request):
    if request.method == 'POST':
        form = JobForm(request.POST, request.FILES)
        if form.is_valid():
            myform = form.save(commit=False)
            myform.owner = request.user
            myform.save()
            return redirect(reverse('jobs:job_list'))

    else:
        form = JobForm()

    context = {

        'form': form

    }
    return render(request, 'job/add_job.html', context)

accounts/templates/profile.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{%block content%}
<!-- bradcam_area  -->
<div class="bradcam_area bradcam_bg_1">
    <div class="container">
        <div class="row">
            <div class="col-xl-12">

            </div>
        </div>
    </div>
</div>
<!--/ bradcam_area  -->

<div class="job_details_area">
    <div class="container">
        <div class="row">

            <div class="col-lg-8 mx-auto ">
                <div class="job_sumary ">
                    <div class="summery_header row justify-content-center">
                        <h3>Profile Summery</h3>
                    </div>
                    <div class="job_content">
                        <ul>
                            <li>name: <span>{{profile}}</span></li>
                            <li>Phone Number: <span>{{profile.phone_number}}</span></li>
                            <li>E-mail: <span>{{profile.user.email}}</span></li>

                        </ul>
                        <div class="p-5">
                            <a href="{% url 'accounts:profile_edit' %}" class="boxed-btn3 w-100">Edit Profile</a>
                        </div>
                    </div>
                </div>


            </div>
        </div>
    </div>
</div>
{% endblock %}

accounts/templates/profile_edit.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{%block content%}
<!-- bradcam_area  -->
<div class="bradcam_area bradcam_bg_1">
    <div class="container">

    </div>
</div>
<!--/ bradcam_area  -->

<div class="job_details_area">
    <div class="container">
        <div class="row">
            <div class="col-lg-8">


                <div class="apply_job_form white-bg">
                    <h4>Profile Edit</h4>
                    {# Display a form #}

                    <form method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% bootstrap_form userform %}
                        {% bootstrap_form profileform %}

                        {% buttons %}

                        <button class="boxed-btn3 w-100" type="submit">Save Now</button>

                        {% endbuttons %}
                    </form>

                </div>
            </div>
            <div class="col-lg-4">



            </div>
        </div>
    </div>
</div>
{% endblock %}

contact/templates/contact.html
{% extends 'base.html' %}





{%block content%}

<!-- bradcam_area  -->
<div class="bradcam_area bradcam_bg_1">
    <div class="container">
        <div class="row">
            <div class="col-xl-12">
                <div class="bradcam_text">
                    <h3>contact</h3>
                </div>
            </div>
        </div>
    </div>
</div>
<!--/ bradcam_area  -->
<!-- ================ contact section start ================= -->
<section class="contact-section section_padding">
    <div class="container">



        <div class="row">
            <div class="col-12">
                <h2 class="contact-title">Get in Touch</h2>
            </div>
            <div class="col-lg-8">
                <form class="form-contact contact_form" method="post" novalidate=" novalidate">
                    {% csrf_token %}

                    <div class="row">
                        <div class="col-12">
                            <div class="form-group">
                                <input class="form-control" name="subject" id="subject" type="text"
                                    onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter Subject'"
                                    placeholder='Enter Subject'>
                            </div>
                        </div>
                        <div class="col-sm-12">
                            <div class="form-group">
                                <input class="form-control" name="email" id="email" type="email"
                                    onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter email address'"
                                    placeholder='Enter email address'>
                            </div>
                        </div>
                        <div class="col-12">
                            <div class="form-group">

                                <textarea class="form-control w-100" name="message" id="message" cols="30" rows="9"
                                    onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter Message'"
                                    placeholder='Enter Message'></textarea>
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="form-group">

                            </div>
                        </div>


                    </div>
                    <div class="form-group mt-3">
                        <button type="submit" class="button button-contactForm btn_4 boxed-btn">Send Message</button>
                    </div>
                </form>
            </div>
            <div class="col-lg-4">
                <div class="media contact-info">
                    <span class="contact-info__icon"><i class="ti-home"></i></span>
                    <div class="media-body">
                        <h3>Egypt , Mansoura .</h3>
                        <p>Gehan Street</p>
                    </div>
                </div>
                <div class="media contact-info">
                    <span class="contact-info__icon"><i class="ti-tablet"></i></span>
                    <div class="media-body">
                        <h3>+201124250328</h3>
                        <p>Sat to Thr 9am to 6pm</p>
                    </div>
                </div>
                <div class="media contact-info">
                    <span class="contact-info__icon"><i class="ti-email"></i></span>
                    <div class="media-body">
                        <h3>omar.bendary1996@gamil.com</h3>
                        <p>Send us your query anytime!</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- ================ contact section end ================= -->
{% endblock %}

job/templates/job/job_list.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

<!-- bradcam_area  -->
<div class="bradcam_area bradcam_bg_1">
    <div class="container">
        <div class="row">
            <div class="col-xl-12">
                <div class="bradcam_text">
                    <h3>{{jobs_num.count}} Jobs Available</h3>
                </div>
            </div>
        </div>
    </div>
</div>
<!--/ bradcam_area  -->

<!-- job_listing_area_start  -->
<div class="job_listing_area plus_padding">
    <div class="container">
        <div class="row">
            <div class="col-lg-3">
                <div class="job_filter white-bg">
                    <div class="form_inner white-bg">
                        <h3>Filter</h3>
                        <form method="GET">
                            {% bootstrap_form jobs_filter.form %}
                            <button class="boxed-btn3 w-100 mt-4" type="submit">Search</button>


                        </form>
                    </div>

                </div>
            </div>
            <div class="col-lg-9">
                <div class="recent_joblist_wrap">
                    <div class="recent_joblist white-bg ">
                        <div class="row align-items-center">
                            <div class="col-md-6">
                                <h4>Job Listing</h4>
                            </div>

                        </div>
                    </div>
                </div>
                {% for job in jobs %}


                <div class="job_lists m-0">
                    <div class="row">
                        <div class="col-lg-12 col-md-12">
                            <div class="single_jobs white-bg d-flex justify-content-between">
                                <div class="jobs_left d-flex align-items-center">
                                    <div class="thumb">
                                        <img src="" alt="">
                                    </div>
                                    <div class="jobs_conetent">
                                        <a href="{% url 'jobs:job_detail' job.slug %}">
                                            <h4>{{job.title}}</h4>
                                        </a>
                                        <div class="links_locat d-flex align-items-center">
                                            <div class="location">
                                                <p> <i class="fa fa-map-marker"></i> California, USA</p>
                                            </div>
                                            <div class="location">
                                                <p> <i class="fa fa-clock-o"></i> {{job.job_type}}</p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="jobs_right">
                                    <div class="apply_now">
                                        <a class="heart_mark" href="#"> <i class="fa fa-heart"></i> </a>
                                        <a href="{% url 'jobs:job_detail' job.slug %}" class="boxed-btn3">Apply Now</a>
                                    </div>
                                    <div class="date">
                                        <p>{{job.published_at|date:'d M o'}}</p>
                                    </div>
                                </div>
                            </div>
                        </div>

                    </div>
                    {% endfor %}


                    {% if jobs.has_other_pages %}
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="pagination_wrap">
                                <ul>
                                    {% if jobs.has_previous %}
                                    <li><a href="?page={{ jobs.previous_page_number }}"> <i class="ti-angle-left"></i>
                                        </a></li>
                                    {% endif %}

                                    {% for i in jobs.paginator.page_range %}
                                    <li><a href="?page={{i}}"><span>{{i}}</span></a></li>
                                    {% endfor %}


                                    {% if jobs.has_next %}
                                    <li><a href="?page={{ jobs.next_page_number }}"> <i class="ti-angle-right"></i> </a>
                                    </li>
                                    {% endif %}
                                </ul>
                            </div>
                        </div>
                    </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>
<!-- job_listing_area_end  -->

{% endblock %}

templates/base.html
{% load static %}
<!doctype html>
<html class="no-js" lang="zxx">

<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Job Board</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- <link rel="manifest" href="site.webmanifest"> -->
    <link rel="shortcut icon" type="image/x-icon" href="img/favicon.png">
    <!-- Place favicon.ico in the root directory -->

    <!-- CSS here -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/themify-icons.css' %}">
    <link rel="stylesheet" href="{% static 'css/nice-select.css' %}">
    <link rel="stylesheet" href="{% static 'css/flaticon.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}">
    <link rel="stylesheet" href="{% static 'css/gijgo.css' %}">
    <link rel="stylesheet" href="{% static 'css/animate.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/slicknav.css' %}">

    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <!-- <link rel="stylesheet" href="css/responsive.css"> -->
</head>

<body>


    <!-- header-start -->
    <header>
        <div class="header-area ">
            <div id="sticky-header" class="main-header-area">
                <div class="container-fluid ">
                    <div class="header_bottom_border">
                        <div class="row align-items-center">
                            <div class="col-xl-3 col-lg-2">
                                <div class="logo">
                                    <a href="index.html">
                                        <img src="img/logo.png" alt="">
                                    </a>
                                </div>
                            </div>
                            <div class="col-xl-6 col-lg-7">
                                <div class="main-menu  d-none d-lg-block">
                                    <nav>
                                        <ul id="navigation">
                                            <li><a href="/">home</a></li>
                                            <li><a href="{% url 'jobs:job_list'%}">Browse Job</a></li>
                                            <li><a href="{% url 'contact:contact'%}">Contact</a></li>
                                        </ul>
                                    </nav>
                                </div>
                            </div>
                            <div class="col-xl-3 col-lg-3 d-none d-lg-block">
                                <div class="Appointment">


                                    {% if request.user.is_authenticated %}
                                    <div class="phone_num d-none d-xl-block">
                                        <a href="{% url 'logout'%}">Log out</a>
                                    </div>
                                    <div class="phone_num d-none d-xl-block">
                                        <a href="{% url 'accounts:profile'%}">Profile</a>
                                    </div>


                                    {% else %}
                                    <div class="phone_num d-none d-xl-block">
                                        <a href="{% url 'login'%}">Log in</a>
                                    </div>

                                    {% endif %}



                                    <div class="d-none d-lg-block">
                                        <a class="boxed-btn3" href="{% url 'jobs:add_job' %}">Post a Job</a>
                                    </div>
                                </div>
                            </div>
                            <div class="col-12">
                                <div class="mobile_menu d-block d-lg-none"></div>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </header>
    <!-- header-end -->

    {%block content%}
    {% endblock %}

    <!-- footer start -->
    <footer class="footer">
        <div class="footer_top">
            <div class="container">
                <div class="row">
                    <div class="col-xl-3 col-md-6 col-lg-3">
                        <div class="footer_widget wow fadeInUp" data-wow-duration="1s" data-wow-delay=".3s">
                            <div class="footer_logo">
                                <a href="#">
                                    <img src="img/logo.png" alt="">
                                </a>
                            </div>
                            <p>
                                finloan@support.com <br>
                                +10 873 672 6782 <br>
                                600/D, Green road, NewYork
                            </p>
                            <div class="socail_links">
                                <ul>
                                    <li>
                                        <a href="#">
                                            <i class="ti-facebook"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            <i class="fa fa-google-plus"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            <i class="fa fa-twitter"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            <i class="fa fa-instagram"></i>
                                        </a>
                                    </li>
                                </ul>
                            </div>

                        </div>
                    </div>
                    <div class="col-xl-2 col-md-6 col-lg-2">
                        <div class="footer_widget wow fadeInUp" data-wow-duration="1.1s" data-wow-delay=".4s">
                            <h3 class="footer_title">
                                Company
                            </h3>
                            <ul>
                                <li><a href="#">About </a></li>
                                <li><a href="#"> Pricing</a></li>
                                <li><a href="#">Carrier Tips</a></li>
                                <li><a href="#">FAQ</a></li>
                            </ul>

                        </div>
                    </div>
                    <div class="col-xl-3 col-md-6 col-lg-3">
                        <div class="footer_widget wow fadeInUp" data-wow-duration="1.2s" data-wow-delay=".5s">
                            <h3 class="footer_title">
                                Category
                            </h3>
                            <ul>
                                <li><a href="#">Design & Art</a></li>
                                <li><a href="#">Engineering</a></li>
                                <li><a href="#">Sales & Marketing</a></li>
                                <li><a href="#">Finance</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-xl-4 col-md-6 col-lg-4">
                        <div class="footer_widget wow fadeInUp" data-wow-duration="1.3s" data-wow-delay=".6s">
                            <h3 class="footer_title">
                                Subscribe
                            </h3>
                            <form action="#" class="newsletter_form">
                                <input type="text" placeholder="Enter your mail">
                                <button type="submit">Subscribe</button>
                            </form>
                            <p class="newsletter_text">Esteem spirit temper too say adieus who direct esteem esteems
                                luckily.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="copy-right_text wow fadeInUp" data-wow-duration="1.4s" data-wow-delay=".3s">
            <div class="container">
                <div class="footer_border"></div>
                <div class="row">
                    <div class="col-xl-12">
                        <p class="copy_right text-center">
                            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                            Copyright &copy;
                            <script>document.write(new Date().getFullYear());</script> All rights reserved | This
                            template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a
                                href="https://colorlib.com" target="_blank">Colorlib</a>
                            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!--/ footer end  -->

    <!-- link that opens popup -->
    <!-- JS here -->
    <script src="{% static 'js/vendor/modernizr-3.5.0.min.js' %}"></script>
    <script src="{% static 'js/vendor/jquery-1.12.4.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/isotope.pkgd.min.js' %}"></script>
    <script src="{% static 'js/ajax-form.js' %}"></script>
    <script src="{% static 'js/waypoints.min.js' %}"></script>
    <script src="{% static 'js/jquery.counterup.min.js' %}"></script>
    <script src="{% static 'js/imagesloaded.pkgd.min.js' %}"></script>
    <script src="{% static 'js/scrollIt.js' %}"></script>
    <script src="{% static 'js/jquery.scrollUp.min.js' %}"></script>
    <script src="{% static 'js/wow.min.js' %}"></script>
    <script src="{% static 'js/nice-select.min.js' %}"></script>
    <script src="{% static 'js/jquery.slicknav.min.js' %}"></script>
    <script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
    <script src="{% static 'js/plugins.js'"></script>
    <!-- <script src="js/gijgo.min.js"></script> -->
    <script src="{% static 'js/range.js' %}"></script>



    <!--contact js-->
    <script src="{% static 'js/contact.js' %}"></script>
    <script src="{% static 'js/jquery.ajaxchimp.min.js' %}"></script>
    <script src="{% static 'js/jquery.form.js' %}"></script>
    <script src="{% static 'js/jquery.validate.min.js' %}"></script>
    <script src="{% static 'js/mail-script.js' %}"></script>


    <script src="{% static 'js/main.js' %}"></script>


    <script>
        $(function () {
            $("#slider-range").slider({
                range: true,
                min: 0,
                max: 24600,
                values: [750, 24600],
                slide: function (event, ui) {
                    $("#amount").val("$" + ui.values[0] + " - $" + ui.values[1] + "/ Year");
                }
            });
            $("#amount").val("$" + $("#slider-range").slider("values", 0) +
                " - $" + $("#slider-range").slider("values", 1) + "/ Year");
        });
    </script>
</body>

</html>

templates/base_generic.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{%block content%}
<!-- bradcam_area  -->
<div class="bradcam_area bradcam_bg_1">
    <div class="container">
        <div class="row">
            <div class="col-xl-12">
                <div class="bradcam_text">
                    <h3>{{job.title}}</h3>
                </div>
            </div>
        </div>
    </div>
</div>
<!--/ bradcam_area  -->

<div class="job_details_area">
    <div class="container">
        <div class="row">
            <div class="col-lg-8">


                {% block content_body %}
                {% endblock content_body %}
            </div>
            <div class="col-lg-4">



            </div>
        </div>
    </div>
</div>
{% endblock %}